server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: backend-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      # เก็บเฉพาะ container ชื่อ java-backend
      - source_labels: [__meta_docker_container_name]
        regex: '/java-backend'
        action: keep

      # set label ชื่อ container
      - source_labels: [__meta_docker_container_name]
        target_label: container

      # อ่านไฟล์ log
      - source_labels: [__meta_docker_container_log_path]
        target_label: __path__
